### ISSUE TITLE
read-only filesystem

### ISSUE THREAD

**Issue by bobmorane77** [robertdebock/docker-debian-systemd#2]
hi,
i tried your dockerfile an run commands.
I get bullseye, what ok ist, but on start docker i get

Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...

**Comment by ghost** [comment]
Hi,
I have the same probleme

**Comment by cclecle** [comment]
same

**Comment by robertdebock** [comment]
That's correct. These docker containers are used to test Ansible roles. They require more permissions and mounts to run.

I would suggest to use a "regular" container for day-to-day work.
